const fs = require('fs');
const path = require('path');

const pagesPath = path.join(__dirname, '..', 'public', 'js', 'pages.js');
let content = fs.readFileSync(pagesPath, 'utf8');

const dict = {
    'QUẢN LÝ THIẾT BỊ (EDGE GATEWAY)': 'DEVICE MANAGEMENT (EDGE GATEWAY)',
    'Tìm kiếm Gateway, SSID...': 'Search Gateway, SSID...',
    '➕ Thêm Gateway Mới': '➕ Add New Gateway',
    '>_ TRẠM ĐIỀU KHIỂN & GIÁM SÁT GIAO THỨC MQTT (REAL-TIME)': '>_ MQTT PROTOCOL MONITORING & CONTROL STATION (REAL-TIME)',
    'Đang khởi tạo kết nối giám sát...': 'Initializing monitoring connection...',
    'ID Gateway (Mã thiết bị)': 'Gateway ID (Device Code)',
    'Nhập ID, vd: GW001': 'Enter ID, e.g.: GW001',
    'Mật khẩu Gateway': 'Gateway Password',
    'Nhập mật khẩu': 'Enter password',
    'Hủy Bỏ': 'Cancel',
    'Hủy': 'Cancel',
    'Xác nhận': 'Confirm',
    'CÀI ĐẶT TÀI KHOẢN': 'ACCOUNT SETTINGS',
    'THÔNG TIN CÁ NHÂN': 'PERSONAL INFORMATION',
    'Địa chỉ Email': 'Email Address',
    'Họ và Tên (*)': 'Full Name (*)',
    'Số điện thoại': 'Phone Number',
    'CẬP NHẬT THÔNG TIN': 'UPDATE INFORMATION',
    'ĐỔI MẬT KHẨU': 'CHANGE PASSWORD',
    'Mật khẩu hiện tại': 'Current Password',
    'Mật khẩu mới': 'New Password',
    'Xác nhận mật khẩu mới': 'Confirm New Password',
    'CẤU HÌNH MẠNG WI-FI TỪ XA': 'REMOTE WI-FI NETWORK CONFIGURATION',
    'THÔNG TIN WI-FI MỚI': 'NEW WI-FI INFORMATION',
    'Chọn Thiết Bị Gateway (*)': 'Select Gateway Device (*)',
    'Đang tải thiết bị...': 'Loading devices...',
    'Tên Wi-Fi (SSID) mới (*)': 'New Wi-Fi Name (SSID) (*)',
    'Nhập tên mạng': 'Enter network name',
    'Nhập mật khẩu (Nút mắt nhấp nháy)': 'Enter password',
    'GỬI CẤU HÌNH XUỐNG THIẾT BỊ': 'SEND CONFIG TO DEVICE',
    '⚠️ XÁC NHẬN ĐỔI MẠNG': '⚠️ CONFIRM NETWORK CHANGE',
    'Bạn có chắc chắn muốn đổi mạng cho thiết bị này? Nếu nhập sai mật khẩu, thiết bị sẽ tự động khôi phục mạng cũ sau 15 giây.': 'Are you sure you want to change the network for this device? If the password is wrong, it will automatically revert to the old network after 15 seconds.',
    'Tôi Chắc Chắn': 'I Am Sure',
    'Chức năng Đăng ký đã bị khóa': 'Registration is locked',
    'Vui lòng liên hệ Quản trị viên để được cấp tài khoản.': 'Please contact the Administrator for an account.',
    '⬅ Quay lại Đăng nhập': '⬅ Back to Login',
    'ĐĂNG NHẬP VỚI GOOGLE': 'LOGIN WITH GOOGLE',
    'ĐĂNG NHẬP': 'LOGIN',
    'HOẶC': 'OR',
    'Quản lý thiết bị': 'Device Management',
    'Cấu hình mạng': 'Network Configuration',
    'Quản lý người dùng': 'User Management',
    'Cài đặt tài khoản': 'Account Settings',
    'Đăng xuất': 'Logout',
    'TRẠM QUAN TRẮC 1 (Node 1)': 'MONITORING STATION 1 (Node 1)',
    'TRẠM QUAN TRẮC 2 (Node 2)': 'MONITORING STATION 2 (Node 2)',
    'Cập nhật lúc:': 'Last updated:',
    'Nồng độ SO2': 'SO2 Concentration',
    'Bụi mịn PM2.5': 'PM2.5 Fine Dust',
    'Bụi PM10': 'PM10 Dust',
    'Bụi PM1.0': 'PM1.0 Dust',
    'THÔNG TIN & CẤU HÌNH GATEWAY': 'GATEWAY INFO & CONFIGURATION',
    'Trạng thái kết nối': 'Connection Status',
    'Ngưỡng cảnh báo SO2': 'SO2 Warning Threshold',
    'Ngưỡng cảnh báo Bụi (PM)': 'Dust (PM) Warning Threshold',
    'Mạng kết nối (SSID)': 'Connected Network (SSID)',
    'Cường độ WiFi (RSSI)': 'WiFi Signal Strength (RSSI)',
    'Máy chủ MQTT': 'MQTT Server',
    'Cổng giao tiếp (Port)': 'Communication Port',
    'Chu kỳ Heartbeat': 'Heartbeat Interval',
    'Tên thiết bị (OTA)': 'Device Name (OTA)',
    'BIỂU ĐỒ XU HƯỚNG THỜI GIAN THỰC': 'REAL-TIME TREND CHARTS',
    'Hiển thị: Cả 2 Zone': 'Display: Both Zones',
    'Chỉ hiển thị Node 1': 'Display Node 1 Only',
    'Chỉ hiển thị Node 2': 'Display Node 2 Only',
    'Chỉ hiện Node 1 (N1)': 'Display Node 1 (N1) Only',
    'Chỉ hiện Node 2 (N2)': 'Display Node 2 (N2) Only',
    'Hiển thị: Tất cả Trạm': 'Display: All Stations',
    'NHẬT KÝ SỰ KIỆN': 'EVENT LOG',
    'Tất cả': 'All',
    'Vượt ngưỡng': 'Threshold Exceeded',
    'Kết nối': 'Connection',
    'Thời gian': 'Time',
    'Nguồn': 'Source',
    'Chi tiết': 'Details',
    'SO2 vượt ngưỡng': 'SO2 exceeded threshold',
    'Khôi phục WebSocket': 'WebSocket Restored',
    'THỐNG KÊ ĐỘ ỔN ĐỊNH': 'STABILITY STATISTICS',
    'Hôm nay (Live)': 'Today (Live)',
    'Trong tuần': 'This Week',
    'Trong tháng': 'This Month',
    'Trong năm': 'This Year',
    'sự cố': 'incidents',
    'QUẢN LÝ QUYỀN TRUY CẬP (ACCESS CONTROL)': 'ACCESS CONTROL MANAGEMENT',
    'THÊM NGƯỜI DÙNG MỚI': 'ADD NEW USER',
    '1. Thông tin người nhận': '1. Recipient Information',
    'Nhập địa chỉ Email (VD: kythuat@factory.com)...': 'Enter Email address (e.g. tech@factory.com)...',
    '2. Quyền xem dữ liệu trạm (View Access)': '2. Station Data View Access',
    'Cho phép xem số liệu SO2, Bụi của ống khói 1': 'Allow viewing SO2 and Dust data of chimney 1',
    'Cho phép xem số liệu SO2, Bụi của ống khói 2': 'Allow viewing SO2 and Dust data of chimney 2',
    '3. Quyền quản trị hệ thống (Admin Access)': '3. System Admin Access',
    'Chỉnh sửa Ngưỡng cảnh báo': 'Edit Warning Thresholds',
    'Cho phép thay đổi giới hạn SO2 và Bụi (Publish MQTT)': 'Allow changing SO2 and Dust limits (Publish MQTT)',
    'Xem thông tin Gateway': 'View Gateway Information',
    'Xem IP, RSSI, MQTT Status, Uptime của thiết bị tổng': 'View IP, RSSI, MQTT Status, Uptime of main device',
    'Cấu hình WiFi': 'WiFi Configuration',
    'Quyền gửi lệnh Reset cấu hình mạng ESP-01': 'Permission to send Reset network config command to ESP-01',
    'Gửi lời mời & Cấp quyền': 'Send Invite & Grant Access',
    'DANH SÁCH TÀI KHOẢN ĐÃ ĐƯỢC CHIA SẺ': 'LIST OF SHARED ACCOUNTS',
    'Tổng: 2 người': 'Total: 2 people',
    'Tài khoản Email': 'Email Account',
    'Khu vực giám sát (Nodes)': 'Monitored Areas (Nodes)',
    'Quyền quản trị mở rộng': 'Extended Admin Rights',
    'Hành động': 'Action',
    'Sửa Ngưỡng': 'Edit Thresholds',
    'Thu hồi': 'Revoke',
    'Chỉ xem': 'View Only',
    'PHÂN TÍCH DỮ LIỆU': 'DATA ANALYSIS',
    '📂 Nhập file Log (.txt)': '📂 Import Log file (.txt)',
    '📥 Xuất CSV (Bản đang xem)': '📥 Export CSV (Current View)',
    'BÁO CÁO THỐNG KÊ TỔNG QUAN (SUMMARY)': 'OVERVIEW STATISTICAL REPORT (SUMMARY)',
    'Chưa có dữ liệu': 'No data yet',
    'Thông tin Dữ liệu': 'Data Information',
    'Tổng số bản ghi:': 'Total records:',
    'Bản ghi Node 1:': 'Node 1 records:',
    'Bản ghi Node 2:': 'Node 2 records:',
    'Trung bình (Avg):': 'Average (Avg):',
    'Thấp nhất (Min):': 'Minimum (Min):',
    'Cao nhất (Max):': 'Maximum (Max):',
    'Vượt ngưỡng (>100):': 'Exceeded threshold (>100):',
    'Vượt ngưỡng (>250):': 'Exceeded threshold (>250):',
    'lần': 'times',
    'DỮ LIỆU CẢM BIẾN CHI TIẾT (RAW DATA)': 'DETAILED SENSOR DATA (RAW DATA)',
    'STT': 'No.',
    'Trạm (Zone)': 'Station (Zone)',
    'Chưa có dữ liệu. Vui lòng nhấn "Nhập file Log" để bắt đầu phân tích.': 'No data. Please click "Import Log file" to start analysis.',
    'Tính năng này đang trong quá trình phát triển UI. Chú trọng module Dashboard (Socket) trước.': 'This feature is under UI development. Focusing on Dashboard module (Socket) first.',
    'QUẢN LÝ NGƯỜI DÙNG (ADMIN ONLY)': 'USER MANAGEMENT (ADMIN ONLY)',
    'TẠO TÀI KHOẢN MỚI': 'CREATE NEW ACCOUNT',
    'Tên nhân viên': 'Employee Name',
    'Mật khẩu khởi tạo': 'Initial Password',
    'Phân quyền': 'Role',
    'Nhân viên (User)': 'Employee (User)',
    'Quản trị viên (Admin)': 'Administrator (Admin)',
    'Tạo Tài Khoản': 'Create Account',
    'DANH SÁCH TÀI KHOẢN TRONG HỆ THỐNG': 'LIST OF ACCOUNTS IN THE SYSTEM',
    'Tên': 'Name',
    'Quyền (Role)': 'Role',
    'Ngày tạo': 'Created Date',
    'Đang tải dữ liệu...': 'Loading data...'
};

for (const [vn, en] of Object.entries(dict)) {
    // Replace globally
    content = content.split(vn).join(en);
}

fs.writeFileSync(pagesPath, content, 'utf8');
console.log('Pages translated successfully');
